type CritiqueSection = {
  id: string;
  heading: string;
  paragraphs: string[];
};

const CRITIQUE_SECTIONS: CritiqueSection[] = [
  {
    id: "01",
    heading: "Dataset Scope and Variables",
    paragraphs: [
      "This dataset contains detailed records of fatal police shootings in the United States. Each entry includes information about the death itself, such as an ID number, date, whether body camera footage exists, city, county, state, latitude, longitude, and the precision of the location. It also includes information about the person who was killed. Victim variables include name, age, gender, race, the source used to determine race, whether the incident was related to mental illness, the type of threat reported, whether the person was armed and with what, flee status, and agency identifiers. The dataset also includes a separate set of agency level data. These fields include agency ID, agency name, agency type, state, ORI codes, and the total number of shootings linked to that agency.",
      "Because of this structure, the dataset can illuminate patterns in fatal police shootings. It allows researchers to examine who is being killed, where these incidents occur, and some of the reported circumstances. The geographic data also makes it possible to study regional trends. Demographic fields allow analysis of age, race, and gender patterns. Variables such as armed status, threat type, and flee status help describe how these encounters are officially framed. The inclusion of agency identifiers also allows comparisons across departments and jurisdictions.",
      "However, the dataset is limited to one very specific outcome. It only documents incidents in which an on duty police officer shoots and kills a civilian. It does not represent all police use of force, and it does not represent all deaths that occur during contact with police.",
    ],
  },
  {
    id: "02",
    heading: "What This Dataset Cannot Reveal",
    paragraphs: [
      "There are several important things this dataset cannot reveal. It does not include the population of each city or state for each year. This means it cannot on its own provide rates or per capita comparisons. It does not include deaths of people in custody, such as deaths in jail cells or during restraint without gunfire. It excludes fatal shootings carried out by off duty officers. It also leaves out incidents in which police fired their weapons but the person survived. As a result, it captures only the most extreme and final outcome, which shapes the kinds of questions that can be asked.",
    ],
  },
  {
    id: "03",
    heading: "How The Dataset Is Produced",
    paragraphs: [
      "The data was generated by The Washington Post. Reporters compiled and maintain the database. They draw on agency data and federal law enforcement datasets. The original sources include information from the FBI and the Department of Justice related to fatal shootings by police. In 2022, The Post made a specific effort to improve agency identification. They worked to increase the coverage of federal Originating Agency Identifier codes. Reporters used both automated and manual matching of names and ORI codes to fill in missing data. This shows that the dataset is not simply downloaded from a single official source. It is assembled through journalistic work, technical matching, and editorial decisions about inclusion and categorization. The creation and maintenance of the dataset is funded by The Washington Post as a media organization.",
    ],
  },
  {
    id: "04",
    heading: "Missing Context and Representation Limits",
    paragraphs: [
      "Important information is left out of the spreadsheet. It does not include broader social context such as poverty levels, local crime rates, or community demographics. It does not provide full medical or legal details about the manner of death beyond the fact that police gunfire was involved. Although there is a variable for whether the incident was related to mental illness, this category is limited and may not capture diagnoses, history, or nuance. Ethnicity is not clearly separated from race, and there may be no consistent way to represent mixed racial or mixed ethnic identities. This simplifies complex identities into fixed boxes.",
    ],
  },
  {
    id: "05",
    heading: "Ideological Effects of Data Structure",
    paragraphs: [
      "The way this dataset turns events into data has ideological effects. By focusing only on fatal shootings, it centers death by gunfire as the key measure of police violence. Other forms of harm become less visible. The structure also relies on official or media reported categories such as threat type or armed status. These categories may reflect law enforcement narratives or early reports rather than full investigations. The ontology of the dataset treats each incident as a discrete event tied to an individual victim. It does not capture long histories of community police relations or systemic conditions. If this dataset were the only source, we would know who died in these shootings and some basic details. We would not know how often police use force without killing, how communities experience policing more broadly, or how structural factors shape these encounters. The dataset is powerful, but it is shaped by choices about what counts as data and what does not.",
    ],
  },
];

export default function DataCritiquePage() {
  return (
    <main className="mx-auto w-full max-w-[1200px] border-x border-black font-[family:var(--font-nav)]">
      <header className="border-b border-black px-6 py-10 sm:px-10 sm:py-14">
        <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-black/70">Data</p>
        <h1 className="mt-4 max-w-4xl font-[family:var(--font-masthead)] text-4xl font-semibold leading-[1.05] sm:text-6xl">
          Data Critique
        </h1>
        <p className="mt-5 max-w-3xl text-base leading-relaxed text-black/75">
          An analysis of what the fatal police shootings dataset makes visible, what it excludes, and how those
          choices shape interpretation across this project.
        </p>
      </header>

      {CRITIQUE_SECTIONS.map((section, index) => (
        <section
          key={section.id}
          className={`grid gap-0 lg:grid-cols-[150px_1fr] ${
            index < CRITIQUE_SECTIONS.length - 1 ? "border-b border-black" : ""
          }`}
        >
          <aside className="border-b border-black px-6 py-6 sm:px-10 lg:border-r lg:border-b-0 lg:px-6 lg:py-10">
            <p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-black/55">Section</p>
            <p className="mt-3 font-[family:var(--font-masthead)] text-3xl font-semibold leading-none">{section.id}</p>
          </aside>

          <div className="px-6 py-8 sm:px-10 sm:py-10">
            <h2 className="font-[family:var(--font-masthead)] text-3xl font-semibold leading-tight sm:text-4xl">
              {section.heading}
            </h2>
            <div className="mt-6 space-y-5">
              {section.paragraphs.map((paragraph) => (
                <p key={paragraph} className="max-w-5xl text-base leading-relaxed text-black/80">
                  {paragraph}
                </p>
              ))}
            </div>
          </div>
        </section>
      ))}
    </main>
  );
}
